"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="shortcut icon"
        href="/images/snooker-logo.png"
        type="image/x-icon"
      />
      <title>SNOOKER</title>
      <body className={inter.className}>
        <NextTopLoader color="red" />
        {children}
      </body>
    </html>
  );
}
